# Generated by Django 4.2.4 on 2023-08-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audio', models.FileField(upload_to='audio_files/')),
                ('dateOfUpload', models.DateTimeField(auto_now_add=True)),
                ('size', models.FloatField(max_length=200)),
                ('extension', models.CharField(max_length=200)),
            ],
        ),
    ]
