# Generated by Django 4.2.4 on 2023-08-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioExtraction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofeatures',
            name='duration',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
    ]
