# Generated by Django 4.2.4 on 2023-08-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioExtraction', '0005_audiofeatures_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofeatures',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
