# Generated by Django 4.2.4 on 2023-08-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioExtraction', '0006_alter_audiofeatures_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofeatures',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
